--- #YAML:1.0
name:                API-PleskExpand
version:             1.04
abstract:            API::PleskExpand - OOP interface to the Plesk Expand XML API
license:             perl
author:              
    - NRG <pavel.odintsov@googlemail.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    API::Plesk:                    1.04
    Carp:                          0
    Data::Dumper:                  0
    Getopt::Long:                  0
    HTTP::Request:                 0
    LWP::UserAgent:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
